import {
    controlconsole1,
    controlconsole2,
    controlconsole3,
    controlconsole4,
    controlconsole5,
    controlconsole6,
    largehousing1,
    largehousing10,
    largehousing11,
    largehousing12,
    largehousing13,
    largehousing2,
    largehousing3,
    largehousing4,
    largehousing5,
    largehousing6,
    largehousing7,
    largehousing8,
    largehousing9,
    load1,
    load2,
    misc1,
    misc2,
    misc3,
    misc4,
    multidoor1,
    multidoor10,
    multidoor11,
    multidoor12,
    multidoor13,
    multidoor14,
    multidoor15,
    multidoor16,
    multidoor17,
    multidoor18,
    multidoor19,
    multidoor2,
    multidoor3,
    multidoor4,
    multidoor5,
    multidoor6,
    multidoor7,
    multidoor8,
    multidoor9,
    racks1,
    racks2,
    racks3,
    racks4,
    racks5,
    singleDoor1,
    singleDoor2,
    singleDoor3,
    singleDoor4,
    singleDoor5,
    singleDoor6,
    singleDoor7,
    small1,
    small10,
    small11,
    small2,
    small3,
    small4,
    small5,
    small6,
    small7,
    small8,
    small9,
    transformer1,
    transformer2,
    transformer3,
    transformer4,
    transformer5,
  } from "@/constants/imagePath";
  
  export const productsData = [
    {
      id: 1,
      category: "19'' & 24'' Racks",
      products: [
        { id: 1, image: racks1 },
        { id: 2, image: racks2 },
        { id: 3, image: racks3 },
        { id: 4, image: racks4 },
        { id: 5, image: racks5 },
      ],
    },
    {
      id: 2,
      category: "Single Door Enclosures",
      products: [
        { id: 1, image: singleDoor1 },
        { id: 2, image: singleDoor2 },
        { id: 3, image: singleDoor3 },
        { id: 4, image: singleDoor4 },
        { id: 5, image: singleDoor5 },
        { id: 6, image: singleDoor6 },
        { id: 7, image: singleDoor7 },
      ],
    },
    {
        id: 3,
        category: "Multi Door Enclosures",
        products: [
            { id: 1, image: multidoor1 },
            { id: 2, image: multidoor2 },
            { id: 3, image: multidoor3 },
            { id: 4, image: multidoor4 },
            { id: 5, image: multidoor5 },
            { id: 6, image: multidoor6 },
            { id: 7, image: multidoor7 },
            { id: 8, image: multidoor8 },
            { id: 9, image: multidoor9 },
            { id: 10, image: multidoor10 },
            { id: 11, image: multidoor11 },
            { id: 12, image: multidoor12 },
            { id: 13, image: multidoor13 },
            { id: 14, image: multidoor14 },
            { id: 15, image: multidoor15 },
            { id: 16, image: multidoor16 },
            { id: 17, image: multidoor17 },
            { id: 18, image: multidoor18 },
            { id: 19, image: multidoor19 },
        ],
    },
    {
        id: 4,
        category: "Large Housings",
        products: [
            { id: 1, image: largehousing1 },
            { id: 2, image: largehousing2 },
            { id: 3, image: largehousing3 },
            { id: 4, image: largehousing4 },
            { id: 5, image: largehousing5 },
            { id: 6, image: largehousing6 },
            { id: 7, image: largehousing7 },
            { id: 8, image: largehousing8 },
            { id: 9, image: largehousing9 },
            { id: 10, image: largehousing10 },
            { id: 11, image: largehousing11 },
            { id: 12, image: largehousing12 },
            { id: 13, image: largehousing13 },
        ],
    },
    {
        id: 5,
        category: "Transformer Housing",
        products: [
            { id: 1, image: transformer1 },
            { id: 2, image: transformer2 },
            { id: 3, image: transformer3 },
            { id: 4, image: transformer4 },
            { id: 5, image: transformer5 },
        ],
    },
    {
        id: 6,
        category: "Control Consoles",
        products: [
            { id: 1, image: controlconsole1 },
            { id: 2, image: controlconsole2 },
            { id: 3, image: controlconsole3 },
            { id: 4, image: controlconsole4 },
            { id: 5, image: controlconsole5 },
            { id: 6, image: controlconsole6 },
        ],
    },
    {
        id: 7,
        category: "Misc. Parts",
        products: [
            { id: 1, image: misc1 },
            { id: 2, image: misc2 },
            { id: 3, image: misc3 },
            { id: 4, image: misc4 },
        ],
    },
    {
        id: 8,
        category: "Small Boxes & Wallmounts",
        products: [
            { id: 1, image: small1 },
            { id: 2, image: small2 },
            { id: 3, image: small3 },
            { id: 4, image: small4 },
            { id: 5, image: small5 },
            { id: 6, image: small6 },
            { id: 7, image: small7 },
            { id: 8, image: small8 },
            { id: 9, image: small9 },
            { id: 10, image: small10 },
            { id: 11, image: small11 },
        ],
    },
    {
        id: 9,
        category: "Load Banks",
        products: [
            { id: 1, image: load1 },
            { id: 2, image: load2 },

        ],
    },
  ];
  